### ISSUE TITLE
How to use multiple IDs?

### ISSUE THREAD

**Issue by drewbaker** [nuxt-community/gtm-module#1]
Is it possible to have this track multiple IDs?

And can these IDs come from the store? They get set in our CMS and fetched using Apollo on serverInit.

**Comment by pi0** [comment]
Hi @drewbaker. Thanks for reaching out. Actually both are limited by module because of performance reasons and on purpose.

> Is it possible to have this track multiple IDs?

Although [Multiple Containers on a Page](https://developers.google.com/tag-manager/devguide#multiple-containers) started being supported from ~2005, it is advised to keep the number of containers minimal for user performance and it essentially is only limited for a same dataLayer name. It is usually due to organization requirements to set multiple ids but please don't do this! User perf is more valuable!

>  And can these IDs come from the store?

Indeed, async `id` is supported by is only possible to provide via `nuxt.config`. Snippet (like the original version) is decoupled from nuxt runtime and directly injected to HTML.

BTW I would like to hear more about your use cases :)

**Comment by drewbaker** [comment]
I run tech at an agency in Los Angeles called Funkhaus. We do everything in Nuxt and we've built our own WordPress/Nuxt boilerplate, that uses WordPress as a headless CMS to power a Nuxt frontend using Nuxt Apollo as the data layer. We actually have our own version of GTM built into it (that supports multiple IDs and from the store) but I was thinking we could replace it with this official module.

The WordPress part: https://github.com/funkhaus/stackhaus-backend
The Nuxt part: https://github.com/funkhaus/stackhaus ([the GTM part here](https://github.com/funkhaus/stackhaus/blob/master/plugins/google-gtag.client.js))

I hear you on performance, but in reality the client always wants their own tracking ID, then we like to have our own as well. Who "owns" this tracking data is important to clients, so it's not enough to share our ID with them. Several hotel clients like to have multiple tracking IDs split across their own data, and also 3rd party travel promotional company's and booking engines.

**Comment by pi0** [comment]
Hi @drewbaker. Thanks for explaining use case. With 2.1.x+ you can now disable autoInit and call `this.$gtm.init` with multiple ids. Please let me know if any issues was encountering for migration (probably new issue or DM)

**Comment by drewbaker** [comment]
Thanks! Would you recommend running `this.$gtm.init()` in `nuxtServerInit` then? That way we could pull the IDs from the store.

**Comment by pi0** [comment]
Hi @drewbaker. Currently it is not possible to access `$gtm` instance on SSR. I created #7 to track this feature request.
