### ISSUE TITLE
SSR `$gtm`

### ISSUE THREAD

**Issue by pi0** [nuxt-community/gtm-module#7]
- Support calling `$gtm.init` during SSR (inspired by #1)
- (to check possibility / points) Support pushing events or setting args per request

**Comment by nachogarcia** [comment]
I'm having an error `Maximum call stack size exceeded` and after debugging, I can see it's a `TypeError: Cannot read property 'pathname' of undefined` in `var a=google_tag_manager["GTM-XXXXXX"].macro(14).pathname.split(".")`

I'm doing the init in nuxtServerInit, so I guess the issue is related to this.

Nuxt.js config
```
  buildModules: [
    ['@nuxtjs/google-analytics', { id: process.env.GOOGLE_ANALYTICS_ID, disabled: true, checkDuplicatedScript: true }],
    ['@nuxtjs/gtm', { id: process.env.GOOGLE_TAG_MANAGER_ID, enabled: false, scriptDefer: true }]
  ],
```

nuxtServerInit
```
this.$ga.enable()
this.$gtm.init()
```

**Comment by pi0** [comment]
Hi @nachogarcia. GTM SSR support just added by [v2.2.0](https://github.com/nuxt-community/gtm-module/releases/tag/v2.2.0) would you please try it? Also, I think you need to add `autoInit: false` if you want to manually/conditionally enable.

**Comment by nachogarcia** [comment]
Works like a charm! Also, you were right, I needed autoinit instead of enabled.

I just realized that the GA module doesn't support SSR though :P
